// Service areas — ported verbatim from the production export
// (src/data/serviceAreas.ts). Generated by __gen-locations.mjs.
// Route: /kitchen-bath-remodeling/[slug]

export type Location = {
  slug: string;
  city: string;
  longName: string;
  state: 'OH' | 'KY';
  /** 1-3 nearby communities, used for areaServed + local copy */
  nearby: string[];
  /** Optional flavour line — only where the real site has one */
  blurb?: string;
};

export const locations: Location[] = [
  {
    "slug": "west-chester",
    "city": "West Chester",
    "longName": "West Chester Township",
    "state": "OH",
    "nearby": [
      "Liberty Township",
      "Mason"
    ],
    "blurb": "West Chester and Liberty Township are full of homes with great bones and dated kitchens and baths."
  },
  {
    "slug": "mason",
    "city": "Mason",
    "longName": "Mason",
    "state": "OH",
    "nearby": [
      "West Chester",
      "Loveland"
    ]
  },
  {
    "slug": "liberty-township",
    "city": "Liberty Township",
    "longName": "Liberty Township",
    "state": "OH",
    "nearby": [
      "West Chester",
      "Mason"
    ]
  },
  {
    "slug": "hyde-park",
    "city": "Hyde Park",
    "longName": "Hyde Park",
    "state": "OH",
    "nearby": [
      "Oakley",
      "Mt. Lookout"
    ],
    "blurb": "Hyde Park's historic homes deserve craftsmanship that respects their architecture."
  },
  {
    "slug": "oakley",
    "city": "Oakley",
    "longName": "Oakley",
    "state": "OH",
    "nearby": [
      "Hyde Park",
      "Norwood"
    ]
  },
  {
    "slug": "montgomery",
    "city": "Montgomery",
    "longName": "Montgomery",
    "state": "OH",
    "nearby": [
      "Blue Ash",
      "Indian Hill"
    ]
  },
  {
    "slug": "blue-ash",
    "city": "Blue Ash",
    "longName": "Blue Ash",
    "state": "OH",
    "nearby": [
      "Montgomery",
      "Sharonville"
    ]
  },
  {
    "slug": "loveland",
    "city": "Loveland",
    "longName": "Loveland",
    "state": "OH",
    "nearby": [
      "Mason",
      "Milford"
    ]
  },
  {
    "slug": "milford",
    "city": "Milford",
    "longName": "Milford",
    "state": "OH",
    "nearby": [
      "Loveland",
      "Anderson Township"
    ]
  },
  {
    "slug": "wyoming",
    "city": "Wyoming",
    "longName": "Wyoming",
    "state": "OH",
    "nearby": [
      "Hartwell",
      "Glendale"
    ]
  },
  {
    "slug": "madeira",
    "city": "Madeira",
    "longName": "Madeira",
    "state": "OH",
    "nearby": [
      "Indian Hill",
      "Kenwood"
    ]
  },
  {
    "slug": "indian-hill",
    "city": "Indian Hill",
    "longName": "Indian Hill",
    "state": "OH",
    "nearby": [
      "Madeira",
      "Montgomery"
    ]
  },
  {
    "slug": "anderson-township",
    "city": "Anderson Township",
    "longName": "Anderson Township",
    "state": "OH",
    "nearby": [
      "Mt. Washington",
      "Newtown"
    ]
  },
  {
    "slug": "sharonville",
    "city": "Sharonville",
    "longName": "Sharonville",
    "state": "OH",
    "nearby": [
      "Blue Ash",
      "Springdale"
    ]
  },
  {
    "slug": "fairfield",
    "city": "Fairfield",
    "longName": "Fairfield",
    "state": "OH",
    "nearby": [
      "Hamilton",
      "West Chester"
    ]
  },
  {
    "slug": "hamilton",
    "city": "Hamilton",
    "longName": "Hamilton",
    "state": "OH",
    "nearby": [
      "Fairfield",
      "Liberty Township"
    ]
  },
  {
    "slug": "lebanon",
    "city": "Lebanon",
    "longName": "Lebanon",
    "state": "OH",
    "nearby": [
      "Mason",
      "Springboro"
    ]
  },
  {
    "slug": "springboro",
    "city": "Springboro",
    "longName": "Springboro",
    "state": "OH",
    "nearby": [
      "Lebanon",
      "Centerville"
    ]
  },
  {
    "slug": "norwood",
    "city": "Norwood",
    "longName": "Norwood",
    "state": "OH",
    "nearby": [
      "Oakley",
      "Hyde Park"
    ]
  },
  {
    "slug": "terrace-park",
    "city": "Terrace Park",
    "longName": "Terrace Park",
    "state": "OH",
    "nearby": [
      "Mariemont",
      "Milford"
    ]
  },
  {
    "slug": "mariemont",
    "city": "Mariemont",
    "longName": "Mariemont",
    "state": "OH",
    "nearby": [
      "Terrace Park",
      "Fairfax"
    ]
  },
  {
    "slug": "mount-lookout",
    "city": "Mt. Lookout",
    "longName": "Mt. Lookout",
    "state": "OH",
    "nearby": [
      "Hyde Park",
      "Columbia Tusculum"
    ]
  },
  {
    "slug": "crestview-hills",
    "city": "Crestview Hills",
    "longName": "Crestview Hills",
    "state": "KY",
    "nearby": [
      "Fort Mitchell",
      "Edgewood"
    ]
  },
  {
    "slug": "fort-mitchell",
    "city": "Fort Mitchell",
    "longName": "Fort Mitchell",
    "state": "KY",
    "nearby": [
      "Crestview Hills",
      "Lakeside Park"
    ]
  },
  {
    "slug": "edgewood",
    "city": "Edgewood",
    "longName": "Edgewood",
    "state": "KY",
    "nearby": [
      "Crestview Hills",
      "Fort Wright"
    ]
  },
  {
    "slug": "florence",
    "city": "Florence",
    "longName": "Florence",
    "state": "KY",
    "nearby": [
      "Union",
      "Erlanger"
    ]
  },
  {
    "slug": "union",
    "city": "Union",
    "longName": "Union",
    "state": "KY",
    "nearby": [
      "Florence",
      "Burlington"
    ]
  },
  {
    "slug": "fort-thomas",
    "city": "Fort Thomas",
    "longName": "Fort Thomas",
    "state": "KY",
    "nearby": [
      "Newport",
      "Bellevue"
    ]
  },
  {
    "slug": "erlanger",
    "city": "Erlanger",
    "longName": "Erlanger",
    "state": "KY",
    "nearby": [
      "Florence",
      "Crestview Hills"
    ]
  },
  {
    "slug": "villa-hills",
    "city": "Villa Hills",
    "longName": "Villa Hills",
    "state": "KY",
    "nearby": [
      "Crestview Hills",
      "Fort Mitchell"
    ]
  }
];

export const locationBySlug: Record<string, Location> = Object.fromEntries(
  locations.map((l) => [l.slug, l]),
);
