// Service-page content — ported verbatim from the production export
// (speedy-kitchen-copy-5a2fe50f). Generated by __gen-services.mjs.

export type Faq = { q: string; a: string };
export type IncludeItem = { title: string; body: string };
export type BudgetTier = {
  name: string;
  range: string;
  tagline: string;
  highlight?: boolean;
  includes: string[];
};
export type Budget = {
  title?: string;
  intro?: string;
  footnote?: string;
  tiers: BudgetTier[];
};

export type Service = {
  slug: string;
  name: string;
  short: string;
  image: string;
  order: number;
  metaTitle: string;
  metaDescription: string;
  eyebrow: string;
  title: string;
  region: string;
  whyTitle: string;
  whyBody: string;
  includesTitle: string;
  includes: IncludeItem[];
  turnaroundTitle: string;
  turnaroundBody: string;
  closingQuote: string;
  faqs: Faq[];
  budget: Budget | null;
};

export const serviceList: Service[] = [
  {
    "slug": "bathroom-remodel",
    "name": "Full Bathroom Remodels",
    "short": "Down-to-the-studs bathroom remodels handled by one in-house team. Custom vanities, tile, fixtures and finishes.",
    "image": "/assets/bathroom-hero.webp",
    "order": 1,
    "metaTitle": "Full Bathroom Remodels",
    "metaDescription": "Down-to-the-studs full bathroom remodels with one in-house team, lifetime warranty and a price guarantee. Reimagine your space from the ground up.",
    "eyebrow": "Serving Ohio, Kentucky & Indiana",
    "title": "Full Bathroom Remodel Budget Ranges",
    "region": "",
    "whyTitle": "",
    "whyBody": "",
    "includesTitle": "What Every Full Bathroom Remodels Project Includes",
    "includes": [
      {
        "title": "Price Guarantee",
        "body": "The number you sign for is the number you pay. No change-order surprises mid-project."
      },
      {
        "title": "Mold & Mildew Remediation",
        "body": "We treat what's behind the walls before we close them up — never patched over or hidden."
      },
      {
        "title": "New Plumbing Components",
        "body": "Fresh supply lines, drains and p-traps so your new bathroom truly starts from zero."
      },
      {
        "title": "Subfloor Replacement",
        "body": "If the foundation isn't sound, we rebuild it. Tile only lasts when what's beneath it does."
      },
      {
        "title": "Sealed Waterproof Substrate",
        "body": "Engineered backer board and sealed seams designed to keep moisture out for decades."
      },
      {
        "title": "Lifetime Warranty",
        "body": "Every install is backed for life — because we'd rather build it right than come back twice."
      }
    ],
    "turnaroundTitle": "",
    "turnaroundBody": "",
    "closingQuote": "",
    "faqs": [
      {
        "q": "Is a full remodel worth the investment?",
        "a": "A full remodel is an investment, but it's one that pays back. We're priced competitively for the region, and bathroom remodels consistently rank among the highest-ROI projects you can make to a home — most of our clients recover a meaningful share of the cost at resale."
      },
      {
        "q": "How long will my bathroom be out of commission?",
        "a": "Most full bathroom remodels are completed on-site in just 2–5 days. Our team works efficiently and tells you up front what to expect, so you always know how much longer you'll be sharing the hall bath."
      },
      {
        "q": "How disruptive is it day to day?",
        "a": "We hear this often. Our crew handles demo through final touches in-house — no rotating subs, no strangers in your home for months. We keep the workspace clean every day and are out by 6pm so your evenings stay yours."
      }
    ],
    "budget": {
      "title": "Full Bathroom Remodel Budget Ranges",
      "intro": "Hall baths, primary suites and powder rooms each land at a different price point. These tiers reflect what we typically deliver across the Cincinnati tri-state area — locked with our Price Guarantee.",
      "footnote": "Ranges include design, permits, materials, labor and our lifetime workmanship warranty.",
      "tiers": [
        {
          "name": "Essential Bath",
          "range": "$15K – $25K",
          "tagline": "Hall bath or guest bath refresh — same footprint, modern finishes, fully gutted and rebuilt.",
          "highlight": false,
          "includes": [
            "Full demo to the studs and haul-away",
            "New plumbing supply, drain and p-trap",
            "Subfloor inspection and replacement as needed",
            "Acrylic or fiberglass tub/shower combo",
            "Stock vanity with cultured marble top",
            "New toilet, faucet and accessories",
            "LVP or tile flooring + paint"
          ]
        },
        {
          "name": "Signature Bath",
          "range": "$25K – $40K",
          "tagline": "Our most-built package — tile shower, semi-custom vanity and the upgrades that actually last.",
          "highlight": true,
          "includes": [
            "Custom tile walk-in shower with frameless glass",
            "Schluter waterproofing and built-in niche",
            "Semi-custom vanity with quartz top",
            "Designer faucet, valve and toilet (Kohler / Delta / Moen)",
            "Porcelain tile flooring (heated floor optional)",
            "New lighting, exhaust fan, mirror and accessories",
            "Mold/mildew remediation and waterproof substrate"
          ]
        },
        {
          "name": "Luxury Primary Suite",
          "range": "$40K – $55K+",
          "tagline": "Full primary bath: freestanding tub, custom shower, double vanity and reconfigured layout.",
          "highlight": false,
          "includes": [
            "Layout reconfiguration (walls moved, plumbing relocated)",
            "Freestanding soaker tub with floor-mount filler",
            "Curbless zero-entry tile shower with linear drain",
            "Custom double vanity with stone top and integrated lighting",
            "Heated tile floors and towel warmer",
            "Smart toilet or bidet seat option",
            "Designer tile, stone and metal finishes",
            "Built-in storage, linen tower or water closet"
          ]
        }
      ]
    }
  },
  {
    "slug": "walk-in-showers",
    "name": "Walk-In Showers",
    "short": "From dreadful tub to stunning walk-in shower in as little as one day. Anti-slip ADA bases, Triple-Lock Seam backerboard, lifetime warranty.",
    "image": "/assets/service-walk-in-shower.webp",
    "order": 2,
    "metaTitle": "Walk-In Showers",
    "metaDescription": "Beautiful walk-in showers installed in as little as one day. Anti-slip ADA bases, Triple-Lock Seam backerboard, and a lifetime warranty.",
    "eyebrow": "Serving Ohio, Kentucky & Indiana",
    "title": "Walk-In Showers, Installed In As Little As One Day",
    "region": "In-home estimates across the tri-state area",
    "whyTitle": "From Dreadful Tub to Walk-In Shower in 1 Day",
    "whyBody": "The walk-in shower is our best seller for a reason. The ease of accessibility combined with a beautiful aesthetic can bring any bathroom to life in as little as one day. Pairing our stunning acrylic bases with one of our many wall systems creates a bathroom you'll be proud to show off — and one that will serve you for years to come.",
    "includesTitle": "Every Walk-In Shower Installation Includes",
    "includes": [
      {
        "title": "Price Guarantee",
        "body": "What you sign for is what you pay. No surprises."
      },
      {
        "title": "Mold & Mildew Remediation",
        "body": "We address existing issues before they become bigger problems."
      },
      {
        "title": "New Plumbing Components",
        "body": "New supply lines, drain and p-trap for a clean start."
      },
      {
        "title": "Subfloor Replacement",
        "body": "We make sure your foundation is solid before anything goes on top of it."
      },
      {
        "title": "Triple-Lock Seam Backerboard",
        "body": "Engineered to prevent leaks for a lifetime."
      },
      {
        "title": "Anti-Slip, ADA-Approved Base",
        "body": "Safe, stylish, and built to last."
      },
      {
        "title": "ADA Grab Bars & Seats",
        "body": "Added safety without sacrificing style. Available with your install."
      },
      {
        "title": "Lifetime Warranty",
        "body": "Because we stand behind every install."
      },
      {
        "title": "In-House Installers",
        "body": "No subcontractors. One team from demo to finish."
      }
    ],
    "turnaroundTitle": "Quick Turnaround Guarantee",
    "turnaroundBody": "Most walk-in shower installs are completed in a single day. You won't lose a week of your life — or a week of your bathroom — to your remodel.",
    "closingQuote": "Still on the fence? Give us a call or book an in-home consultation and let's talk through what's possible.",
    "faqs": [],
    "budget": {
      "title": "Walk-In Shower Budget Ranges",
      "intro": "From a fast one-day acrylic conversion to a fully custom tile shower, here's what Cincinnati-area homeowners typically invest. Every quote is locked with our Price Guarantee — no change-order surprises.",
      "footnote": "Ranges reflect typical 5x3 to 6x4 shower footprints. Larger or non-standard layouts are quoted individually.",
      "tiers": [
        {
          "name": "One-Day Conversion",
          "range": "$8K – $13K",
          "tagline": "Tub-to-shower conversion in a single day. Acrylic walls, low-curb base, sliding glass door.",
          "highlight": false,
          "includes": [
            "Tub demo and haul-away",
            "Anti-slip ADA-approved acrylic base",
            "Triple-Lock Seam acrylic wall surround",
            "New shower valve, trim and rainfall head",
            "Sliding or hinged framed glass door",
            "Standard grab bar (optional)",
            "Same-day completion in most homes"
          ]
        },
        {
          "name": "Signature Tile Shower",
          "range": "$13K – $17K",
          "tagline": "Curbless or low-curb tile shower with niches, bench and frameless glass — our most popular build.",
          "highlight": true,
          "includes": [
            "Schluter or KERDI waterproofing system",
            "Porcelain or ceramic tile (12x24 or large format)",
            "Built-in tile niche and accent strip",
            "Built-in bench seat",
            "Frameless glass enclosure",
            "Pressure-balanced valve + handheld + rainfall combo",
            "Linear drain option"
          ]
        },
        {
          "name": "Luxury Spa Shower",
          "range": "$17K – $20K+",
          "tagline": "Curbless walk-in with stone tile, body sprays, steam-ready plumbing and designer glass.",
          "highlight": false,
          "includes": [
            "Curbless zero-entry with linear drain",
            "Natural stone or designer porcelain (book-matched options)",
            "Custom mosaic floor or feature wall",
            "Multi-function thermostatic valve with body sprays",
            "Steam shower rough-in available",
            "Heated tile floor option",
            "Low-iron frameless glass with custom hardware",
            "Smart lighting and exhaust integration"
          ]
        }
      ]
    }
  },
  {
    "slug": "tub-shower-combos",
    "name": "Tub Shower Combos",
    "short": "The best of both worlds. Handcrafted insulated tubs paired with custom wall systems — depths from 13″ to 22″.",
    "image": "/assets/service-tub-combo.webp",
    "order": 3,
    "metaTitle": "Tub Shower Combos",
    "metaDescription": "Versatile tub & shower combinations with handcrafted tubs, spray-foam insulation, depth options 13″–22″ and a lifetime warranty.",
    "eyebrow": "Serving Ohio, Kentucky & Indiana",
    "title": "Versatile Tub Shower Combinations",
    "region": "Built for the way your household actually lives",
    "whyTitle": "The Best of Both Worlds",
    "whyBody": "Whether you're a bath person or not, the tub/shower combo makes sure everyone in the house can do as they please. We offer a wide range of depths and aesthetics to pair with our beautiful wall systems, so you can get the look you want without giving up the functionality you need. Our tubs are handcrafted in the Midwest and include an array of top-of-the-line features built to last.",
    "includesTitle": "Every Tub/Shower Combo Installation Includes",
    "includes": [
      {
        "title": "Price Guarantee",
        "body": "What you sign for is what you pay. No surprises."
      },
      {
        "title": "Mold & Mildew Remediation",
        "body": "We address existing issues before they become bigger problems."
      },
      {
        "title": "New Plumbing Components",
        "body": "New supply lines, drain and p-trap for a clean start."
      },
      {
        "title": "Subfloor Replacement",
        "body": "A solid foundation under everything we install."
      },
      {
        "title": "Triple-Lock Seam Backerboard",
        "body": "Engineered to prevent leaks for a lifetime."
      },
      {
        "title": "Spray Foam Insulated Tub",
        "body": "Keeps your water warmer for longer."
      },
      {
        "title": "Depth Options 13″ to 22″",
        "body": "A size that works for every household."
      },
      {
        "title": "Custom Wall Systems",
        "body": "Tile, stone or solid surface — choose the look you love."
      },
      {
        "title": "Lifetime Warranty",
        "body": "Because we stand behind every install."
      }
    ],
    "turnaroundTitle": "Quick Turnaround Guarantee",
    "turnaroundBody": "Most tub/shower combos are completed in 1–2 days. We respect your time and your home — clean job site, on-time finish, no living-out-of-suitcases.",
    "closingQuote": "Not sure if a combo is right for your space? Book an in-home consult and we'll help you figure it out.",
    "faqs": [],
    "budget": null
  },
  {
    "slug": "walk-in-tubs",
    "name": "Walk-In Tubs",
    "short": "Custom-fabricated walk-in tubs with whirlpool, air spa, in-line heaters and aromatherapy.",
    "image": "/assets/service-walk-in-tub.webp",
    "order": 4,
    "metaTitle": "Walk-In Tubs",
    "metaDescription": "Custom walk-in tubs with whirlpool, air spa, in-line heaters, and aromatherapy. Accessible bathing without sacrificing luxury.",
    "eyebrow": "Serving Ohio, Kentucky & Indiana",
    "title": "Walk-In Tubs Done Right",
    "region": "Custom-fabricated for your home and your needs",
    "whyTitle": "Practicality Meets Functionality",
    "whyBody": "The walk-in tubs of today are quite marvelous. We install state-of-the-art Liquid Accent walk-in tubs, each one custom-fabricated to ensure every feature you need is included. While a walk-in tub is great for safe, easy bathing, it also includes a whole array of therapeutic and spa-like features built right in.",
    "includesTitle": "Installation Package & What's Included",
    "includes": [
      {
        "title": "Whirlpool Jets",
        "body": "Powerful, soothing water massage built into the tub."
      },
      {
        "title": "Air Spa",
        "body": "Thousands of gentle bubbles for a softer therapeutic experience."
      },
      {
        "title": "Combination Massage",
        "body": "Switch between water and air therapy on demand."
      },
      {
        "title": "In-Line Heaters",
        "body": "Keeps your bathwater at the perfect temperature longer."
      },
      {
        "title": "Aromatherapy",
        "body": "Built-in scent diffusion for full sensory relaxation."
      },
      {
        "title": "Price Guarantee",
        "body": "What you sign for is what you pay. No surprises."
      },
      {
        "title": "New Plumbing Components",
        "body": "New supply lines, drain and p-trap for a clean start."
      },
      {
        "title": "Triple-Lock Seam Backerboard",
        "body": "Engineered to prevent leaks for a lifetime."
      },
      {
        "title": "Spray Foam Insulation",
        "body": "Keeps your water warmer for longer."
      },
      {
        "title": "Mold & Mildew Remediation",
        "body": "We address existing issues before closing the walls."
      },
      {
        "title": "Subfloor Replacement (if needed)",
        "body": "Solid foundation before anything else goes in."
      },
      {
        "title": "Lifetime Warranty",
        "body": "Because we stand behind every install."
      }
    ],
    "turnaroundTitle": "Most Walk-In Tubs Installed in 1–3 Days",
    "turnaroundBody": "We measure, fabricate to your specs, and install with one in-house team. You'll be soaking in your new tub before the week is out.",
    "closingQuote": "Aging-in-place doesn't have to mean giving up luxury. Let's build a tub that fits the way you live now — and the way you'll live for years.",
    "faqs": [],
    "budget": null
  },
  {
    "slug": "bathroom-flooring",
    "name": "Bathroom Flooring",
    "short": "Premier flooring installation — luxury vinyl, porcelain tile and natural stone. Waterproof prep, slip-resistant finishes.",
    "image": "/assets/service-flooring.webp",
    "order": 5,
    "metaTitle": "Bathroom Flooring Installation",
    "metaDescription": "Premier bathroom flooring installation. Luxury vinyl, porcelain tile and waterproof options from expert consultation to flawless finish.",
    "eyebrow": "You Can Count On Us",
    "title": "Premier Bathroom Flooring Installation",
    "region": "Serving Cincinnati & Surrounding Areas",
    "whyTitle": "The Foundation of a Beautiful, Functional Bathroom",
    "whyBody": "Your bathroom floor is more than a surface to walk on — it's a critical component that defines the room's functionality, safety, and overall aesthetic. Constant exposure to moisture and heavy foot traffic makes choosing a durable, water-resistant material essential. The right flooring prevents water damage, inhibits mold growth, and provides a safe, slip-resistant surface for your family. Beyond the practical, the perfect floor elevates your space from purely functional to a personal sanctuary.",
    "includesTitle": "From Expert Consultation to Flawless Installation",
    "includes": [
      {
        "title": "In-Home Consultation",
        "body": "We come to you, measure carefully and walk through every option in your space."
      },
      {
        "title": "Material Guidance",
        "body": "Luxury vinyl, porcelain tile, natural stone — we explain the trade-offs honestly."
      },
      {
        "title": "Waterproof Subfloor Prep",
        "body": "We rebuild what's underneath before laying anything beautiful on top."
      },
      {
        "title": "Precision Installation",
        "body": "Tight grout lines, level transitions, clean cuts at every fixture."
      },
      {
        "title": "Heated Floor Option",
        "body": "Add radiant heat at install for a noticeable upgrade in daily comfort."
      },
      {
        "title": "Slip-Resistant Finishes",
        "body": "Texture and finish chosen to stay safe even when wet."
      },
      {
        "title": "Sealed & Protected",
        "body": "Proper sealing on day one means easier cleaning for years."
      },
      {
        "title": "Clean Job Site",
        "body": "Drop cloths, dust control, and a fully cleaned space when we leave."
      },
      {
        "title": "Lifetime Workmanship Warranty",
        "body": "We back our install — not just the materials."
      }
    ],
    "turnaroundTitle": "Most Floors Done in 1–2 Days",
    "turnaroundBody": "We schedule materials before we start, so when our team arrives the work moves fast. Most bathroom floors are fully installed and walkable inside two days.",
    "closingQuote": "The right floor changes the whole room. Let's pick yours together — book an in-home consult, no pressure.",
    "faqs": [],
    "budget": null
  },
  {
    "slug": "kitchens",
    "name": "Kitchen Remodels",
    "short": "Full kitchen remodels — cabinets, countertops, flooring, backsplash and plumbing. The same craftsmanship we bring to every bath.",
    "image": "/assets/service-kitchen.webp",
    "order": 6,
    "metaTitle": "Kitchen Remodeling in Cincinnati, OH",
    "metaDescription": "Expert kitchen remodel Cincinnati services. Bulldog Remodel Group handles cabinets, countertops & flooring. Call (513) 657-3750 to book an estimate.",
    "eyebrow": "Serving Ohio, Kentucky & Indiana",
    "title": "Kitchen Remodeling in Cincinnati, OH",
    "region": "One team, in-house — demo to final hardware",
    "whyTitle": "While We're At It, Let's Take A Look At Your Kitchen",
    "whyBody": "The kitchen is the room a household actually lives in, and it's the work we're proudest of. There's something special about transforming the most-used room in the house into a space that actually works for the people living in it — and looks great doing it. Whether you're starting from scratch or ready for a serious upgrade, the same in-house team handles it from demolition through final hardware, with one contract and one project manager throughout.",
    "includesTitle": "Our Kitchen Remodel Services Include",
    "includes": [
      {
        "title": "Price Guarantee",
        "body": "What you sign for is what you pay. No surprises."
      },
      {
        "title": "Full Demo & Haul Away",
        "body": "We clear it out so we can start fresh."
      },
      {
        "title": "Cabinet Installation",
        "body": "Built to last and designed to impress."
      },
      {
        "title": "Countertop Installation",
        "body": "The finishing touch that ties it all together."
      },
      {
        "title": "Flooring",
        "body": "A foundation that sets the tone for the whole room."
      },
      {
        "title": "Backsplash",
        "body": "The detail that makes everything pop."
      },
      {
        "title": "Drywall Repair & Installation",
        "body": "A clean canvas before anything goes up."
      },
      {
        "title": "Plumbing",
        "body": "Handled in-house, no subcontractors needed."
      },
      {
        "title": "Lifetime Warranty",
        "body": "Because we stand behind every install."
      }
    ],
    "turnaroundTitle": "Most Kitchens Done in About 7 Days",
    "turnaroundBody": "With one in-house team and every material staged before demo day, most full kitchen remodels wrap in roughly one week on-site — not the months other contractors quote.",
    "closingQuote": "Still on the fence? Give us a call or book an in-home consultation and let's talk through what's possible.",
    "faqs": [],
    "budget": {
      "title": "Kitchen Remodel Budget Ranges",
      "intro": "Cincinnati-area kitchens vary widely depending on size, layout changes and finish level. These tiers reflect what we typically deliver across Ohio, Kentucky and Indiana — every project is quoted line-by-line and locked with our Price Guarantee.",
      "footnote": "Ranges include design, materials, labor, permits and our lifetime workmanship warranty.",
      "tiers": [
        {
          "name": "Essential Refresh",
          "range": "$35K – $55K",
          "tagline": "Same footprint, brand-new feel. Ideal for working kitchens that just need a serious update.",
          "highlight": false,
          "includes": [
            "Stock or semi-custom cabinetry, painted or stained",
            "Quartz or granite countertops (Level 1)",
            "New tile backsplash",
            "Single-bowl undermount sink + new faucet",
            "LVP or tile flooring",
            "Paint, trim and fresh lighting fixtures",
            "Demo, haul-away and final clean"
          ]
        },
        {
          "name": "Signature Remodel",
          "range": "$55K – $85K",
          "tagline": "Our most popular package — better cabinets, better stone, smarter layout tweaks.",
          "highlight": true,
          "includes": [
            "Semi-custom cabinetry with soft-close drawers and pull-outs",
            "Quartz countertops (Level 2) with waterfall option",
            "Designer tile backsplash to ceiling",
            "Island reconfiguration or peninsula add",
            "New plumbing rough-ins where needed",
            "Updated electrical, can lights and pendants",
            "Appliance install (gas/electric) + new range hood",
            "Hardwood, engineered or premium tile flooring"
          ]
        },
        {
          "name": "Luxury Build",
          "range": "$85K – $120K+",
          "tagline": "Full gut, walls moved, custom cabinetry, designer finishes. The dream kitchen.",
          "highlight": false,
          "includes": [
            "Wall removal, structural beams and load assessment",
            "Fully custom inset cabinetry, paint-grade or wood",
            "Premium quartz, quartzite or natural stone",
            "Pro-grade appliance package (Wolf, Sub-Zero, Thermador)",
            "Beverage center, walk-in pantry or coffee bar",
            "Custom range hood, paneled fridge and dishwasher",
            "Wide-plank hardwood with custom inlays",
            "Lighting design with dimmer scenes and under-cabinet LEDs"
          ]
        }
      ]
    }
  },
  {
    "slug": "kitchen-remodeling-older-homes",
    "name": "Kitchen Remodels for Older Homes",
    "short": "Pre-war bungalows, mid-century ranches and century farmhouses, brought into the present without losing their character.",
    "image": "/assets/service-kitchen.webp",
    "order": 7,
    "metaTitle": "Kitchen Remodeling for Older Homes in Cincinnati",
    "metaDescription": "Remodeling a kitchen in an older Cincinnati home? Learn what to expect with wiring, plumbing, layout and permits — plus realistic budgets and timelines from Bulldog Remodel Group.",
    "eyebrow": "Older Home Specialists · Cincinnati, OH",
    "title": "Kitchen Remodeling for Older Homes in Cincinnati",
    "region": "Pre-war bungalows, mid-century ranches, century-old farmhouses — they all share one thing: a kitchen built for a very different way of living. Here’s how we bring them into the present without erasing the character that made you love the house.",
    "whyTitle": "Older Homes Need a Different Kind of Remodeler",
    "whyBody": "A kitchen built for a very different way of living needs more than new cabinets. We bring older Cincinnati homes into the present without erasing the character that made you love the house.",
    "includesTitle": "What Every Kitchen Remodeling for Older Homes Project Includes",
    "includes": [],
    "turnaroundTitle": "",
    "turnaroundBody": "",
    "closingQuote": "",
    "faqs": [
      {
        "q": "How much does it cost to remodel a kitchen in an older Cincinnati home?",
        "a": "Most projects we take on fall between $40,000 and $95,000. The wider range vs. a newer home reflects what we usually find behind the walls — electrical, plumbing and minor structural work that almost always needs updating."
      },
      {
        "q": "How long will my kitchen be out of service?",
        "a": "Plan on 6–10 weeks on-site once demo begins, plus 4–6 weeks of design and material lead time before we start. We stage everything in advance so the days the room is unusable are as few as possible."
      },
      {
        "q": "Do I always need to upgrade my electrical panel?",
        "a": "Not always — but if your panel is 100A or smaller, or still has fuses, we'll typically recommend an upgrade so the new kitchen circuits have room to live. We'll tell you straight after the walk-through."
      },
      {
        "q": "Can I keep my original hardwood floors and trim?",
        "a": "Almost always yes. Original oak floors usually refinish beautifully, and period trim and built-ins can be carefully removed, stored, and reinstalled. That kind of detail is what makes an older kitchen feel like it belongs in the house."
      },
      {
        "q": "Do you pull the permits?",
        "a": "Yes. We pull every required Cincinnati and Hamilton County permit and meet the inspectors on-site. You don't deal with the building department at all."
      }
    ],
    "budget": null
  },
  {
    "slug": "basement-remodel",
    "name": "Basement Remodels",
    "short": "Finished basements built by one accountable team — fixed pricing, licensed trades, backed for life.",
    "image": "/assets/basement-hero.webp",
    "order": 8,
    "metaTitle": "Basement Remodeling in Cincinnati, OH",
    "metaDescription": "Full-service basement remodeling in Cincinnati by one accountable team. Finished living spaces, basement bathrooms, wet bars and kitchenettes. Fixed pricing, lifetime workmanship warranty. Call (513) 657-3750 to book an estimate.",
    "eyebrow": "Serving Ohio, Kentucky & Indiana",
    "title": "Basement Remodels",
    "region": "",
    "whyTitle": "",
    "whyBody": "",
    "includesTitle": "What Every Basement Remodels Project Includes",
    "includes": [
      {
        "title": "Fixed pricing, zero surprises.",
        "body": "An itemized contract that includes every material, finish, and scope detail. No mid-project change orders."
      },
      {
        "title": "Design-led, with 3D renderings.",
        "body": "See your finished basement before we build it — no cookie-cutter layouts."
      },
      {
        "title": "Faster, cleaner installs.",
        "body": "An engineered process keeps your project on a tight schedule with daily communication."
      },
      {
        "title": "Lifetime workmanship warranty.",
        "body": "Every element we install is backed for life. If it isn't right, we make it right."
      },
      {
        "title": "Licensed & insured.",
        "body": "Across the Greater Cincinnati area — Ohio and Northern Kentucky."
      }
    ],
    "turnaroundTitle": "",
    "turnaroundBody": "",
    "closingQuote": "",
    "faqs": [
      {
        "q": "How long does a basement remodel take in Cincinnati?",
        "a": "Most finished basements run a few weeks on site depending on size and scope. Because we order and stage every material before day one, the build runs on a tight, predictable schedule with daily updates."
      },
      {
        "q": "Can you add a bathroom or wet bar to my basement?",
        "a": "Yes — it's one of our strengths as a full-service remodeler. Plumbing and electrical are handled in-house as part of one contract."
      },
      {
        "q": "Do you handle design and construction, or just the build?",
        "a": "Both. Our in-house designer plans your layout with 3D renderings, and our team handles demolition through finishing under one accountable roof."
      },
      {
        "q": "What does a basement remodel cost?",
        "a": "It depends on square footage, whether you add a bath or bar, and your finishes. We give you an itemized, fixed-price quote up front so there are no surprises. Book an estimate for an exact number."
      }
    ],
    "budget": null
  },
  {
    "slug": "accessory-dwelling-units",
    "name": "Accessory Dwelling Units (ADU)",
    "short": "Detached guest houses, garage conversions and in-law suites — designed, permitted and built by one accountable team.",
    "image": "/assets/service-adu.webp",
    "order": 9,
    "metaTitle": "Accessory Dwelling Units (ADU)",
    "metaDescription": "ADU design and construction in Cincinnati — detached guest houses, garage conversions and in-law suites. Zoning and permits handled, fixed pricing, lifetime workmanship warranty.",
    "eyebrow": "Serving Ohio, Kentucky & Indiana",
    "title": "Accessory Dwelling Units, Built by One Team",
    "region": "Detached guest houses, garage conversions, and in-law suites across Greater Cincinnati",
    "whyTitle": "A Second Home on Your Own Lot",
    "whyBody": "An ADU is a complete, self-contained living space on the property you already own — a detached backyard cottage, a converted garage, or a finished addition with its own entrance, kitchen and bath. Families use them for aging parents, adult children, guests, a home office, or rental income. They are also the most demanding thing we build: a single project that combines foundation and framing with a full kitchen, a full bathroom, and its own plumbing, electrical and HVAC. That is exactly the work we already do every day — just under one roof instead of two. One contract, one project manager, one accountable team from zoning review to the final walkthrough.",
    "includesTitle": "What Every ADU Project Includes",
    "includes": [
      {
        "title": "Zoning Review First",
        "body": "Before anything is designed, we confirm what your lot actually allows. Rules differ by municipality across the tri-state, so we check yours up front — not after you've paid for drawings."
      },
      {
        "title": "Permits & Inspections Managed",
        "body": "We pull the permits, coordinate every inspection, and keep the paperwork moving so you never have to chase a plans examiner."
      },
      {
        "title": "In-House Design & 3D Renderings",
        "body": "A dedicated designer plans the layout, storage and finishes, and you see the space in 3D before a single board is cut."
      },
      {
        "title": "Foundation & Framing",
        "body": "Slab, footings, framing, roofing and siding for detached builds — or structural, insulation and moisture work for a garage conversion."
      },
      {
        "title": "A Real Kitchen",
        "body": "Full kitchen or kitchenette with cabinetry, countertops, sink and appliance hookups — built to the same standard as the kitchens in our portfolio."
      },
      {
        "title": "A Full Bathroom",
        "body": "Complete bath with shower or tub, vanity, toilet and waterproofed wet areas. Our core trade, handled in-house."
      },
      {
        "title": "Utilities Run & Connected",
        "body": "Plumbing supply and drainage, electrical service and panel work, HVAC, and code-compliant egress, smoke and CO detection."
      },
      {
        "title": "Price Guarantee",
        "body": "The number you sign for is the number you pay. Every material, finish and scope detail is itemized before we break ground."
      },
      {
        "title": "Lifetime Workmanship Warranty",
        "body": "The same Lifetime Workmanship Warranty that backs every project we build backs your ADU. If it isn't right, we make it right."
      }
    ],
    "turnaroundTitle": "Planned Before It's Built",
    "turnaroundBody": "An ADU is a larger build than a single-room remodel, and anyone who promises you a fixed number of days before seeing your lot is guessing. What we do promise is that the schedule is set before demolition starts: zoning confirmed, permits filed, materials ordered and staged, every trade booked. You get a realistic timeline in writing, a dedicated project manager, and daily updates — not a moving target.",
    "closingQuote": "Not sure whether your lot can take an ADU? That's the first thing we'll find out — book an in-home consultation and we'll tell you straight.",
    "faqs": [
      {
        "q": "What exactly is an ADU?",
        "a": "An accessory dwelling unit is a second, self-contained living space on the same lot as your main house. It has its own entrance, kitchen or kitchenette, bathroom, and sleeping area. It can be detached (a backyard cottage), attached (an addition with a private entrance), or a conversion of existing space like a garage or basement."
      },
      {
        "q": "Am I allowed to build one on my property?",
        "a": "That depends on your municipality, your lot size and your zoning district — and it genuinely varies across Cincinnati, Northern Kentucky and Southeast Indiana. We start every ADU project by confirming what your specific lot allows, before you spend anything on design."
      },
      {
        "q": "What can I use it for?",
        "a": "Most of our clients are thinking about aging parents, adult children, long-term guests, a private home office or studio, or rental income. Whether short- or long-term rental is permitted is a local rules question we'll check alongside the zoning review."
      },
      {
        "q": "Is a garage conversion cheaper than building detached?",
        "a": "Usually, yes — you already have a foundation, walls and a roof. The work shifts to insulation, moisture control, utilities, egress and finishes. We'll price both approaches if your lot supports either, so you can compare real numbers rather than guesses."
      },
      {
        "q": "How long does an ADU take?",
        "a": "Longer than a kitchen or bath — you're adding permitting and, for detached builds, foundation and framing. The honest answer is that it depends on your scope and your municipality's review times. We give you a realistic written schedule once zoning and design are settled, and we stage all materials before starting so the build itself runs tight."
      },
      {
        "q": "What does an ADU cost?",
        "a": "It varies more than any other project we do — a garage conversion and a new detached cottage aren't in the same range. Once we've seen your lot and settled the scope, you get one itemized, fixed-price contract covering everything. Book an in-home consultation for a real number."
      },
      {
        "q": "Do you handle design and construction, or just the build?",
        "a": "Both. Our in-house designer plans the layout and finishes with 3D renderings, and our own crews handle the build through final walkthrough — under one contract, with one project manager."
      },
      {
        "q": "Does an ADU add value to my home?",
        "a": "It adds real, permitted, livable square footage and a use case most homes don't have, which buyers notice. As with any addition, quality of workmanship is what protects that value over time — which is why ours is backed for life."
      }
    ],
    "budget": null
  },
  {
    "slug": "barndominiums",
    "name": "Barndominiums",
    "short": "Barn-style homes with open spans and a shop under the same roof — designed, permitted and built by one accountable team.",
    "image": "/assets/service-barndominium.webp",
    "order": 10,
    "metaTitle": "Barndominiums",
    "metaDescription": "Barndominium design and construction around Cincinnati — new builds, shell finish-outs and barn conversions. Zoning and permits handled, fixed pricing, lifetime workmanship warranty.",
    "eyebrow": "Serving Ohio, Kentucky & Indiana",
    "title": "Barndominiums, Built by One Team",
    "region": "New builds, shell finish-outs and barn conversions across the Greater Cincinnati region",
    "whyTitle": "A Barn on the Outside. A Home on the Inside.",
    "whyBody": "A barndominium is a barn-style building finished as a full residence — usually post-frame or steel-framed, with clear spans instead of interior load-bearing walls. That structure is the whole point: without walls holding the roof up, the floor plan is genuinely yours, and a workshop or garage can sit under the same roof as the kitchen. What separates a good one from a cold, echoing metal box is everything that happens after the shell goes up — insulation, moisture control, and interiors built to the same standard as a house. That part is our day job. We handle the site and zoning review, the permits, the shell, and every finish inside it, under one contract with one project manager.",
    "includesTitle": "What Every Barndominium Project Includes",
    "includes": [
      {
        "title": "Site & Zoning Review First",
        "body": "Before anything is designed, we confirm what your parcel allows. Residential use of a post-frame building isn't automatic, and rules differ sharply between townships — we check yours up front."
      },
      {
        "title": "Permits & Inspections Managed",
        "body": "We pull the permits, book every inspection, and keep the paperwork moving so you're not chasing a county office."
      },
      {
        "title": "In-House Design & 3D Renderings",
        "body": "Clear spans mean the layout is wide open. A dedicated designer plans how you'll actually use it, and you see it in 3D before anything is framed."
      },
      {
        "title": "Foundation & Shell",
        "body": "Slab, posts or steel framing, roofing and siding — engineered for your span, your snow load and your site."
      },
      {
        "title": "Insulation & Moisture Control",
        "body": "The step that separates a home from a shed. Closed-cell spray foam, a proper vapor strategy and sealed penetrations, so the building doesn't sweat, drum in the rain, or cost a fortune to heat."
      },
      {
        "title": "A Real Kitchen",
        "body": "Full cabinetry, countertops, appliances and lighting — built to the same standard as the kitchens in our portfolio, not a builder-grade afterthought."
      },
      {
        "title": "Full Bathrooms",
        "body": "Complete baths with waterproofed wet areas, tile, vanities and fixtures. Our core trade, handled in-house."
      },
      {
        "title": "Utilities Run & Connected",
        "body": "Electrical service and panel, plumbing supply and drainage, HVAC sized for an open-span building, plus septic and well coordination where there's no municipal hookup."
      },
      {
        "title": "Fixed Price & Lifetime Warranty",
        "body": "One itemized contract covering every material and scope detail, and the same Lifetime Workmanship Warranty that backs every project we build."
      }
    ],
    "turnaroundTitle": "Planned Before It’s Built",
    "turnaroundBody": "A barndominium is a ground-up build, and the schedule depends on your parcel as much as your plans — utility runs, septic approval and county review times all move the date. So we don't quote a number before we've seen the site. What we do commit to is that the schedule is settled before the slab is poured: zoning confirmed, permits filed, shell package ordered, every trade booked. You get a realistic timeline in writing, a dedicated project manager, and updates as it goes up.",
    "closingQuote": "Wondering whether your land will take one? That's the first thing we'll find out — book an in-home consultation and we'll tell you straight.",
    "faqs": [
      {
        "q": "What exactly is a barndominium?",
        "a": "A barn-style building finished as a full-time residence. Most are post-frame or steel-framed, which means the roof is carried by posts or columns rather than interior walls — so you get large open spans and a floor plan that isn't dictated by structure. Many combine living space with a shop, garage or storage under the same roof."
      },
      {
        "q": "Can I build one on my land?",
        "a": "It depends on the parcel. Zoning has to permit residential use, and some districts treat post-frame buildings differently from conventional houses. Setbacks, minimum square footage, septic capacity and road access all matter too. We check all of it for your specific address before you spend anything on design."
      },
      {
        "q": "Is it cheaper than building a conventional house?",
        "a": "Often, per square foot — a simple envelope and clear spans are efficient to build, and you can enclose a lot of space for the money. But the finishes inside cost what finishes cost, and rural sites can add expense a city lot doesn't: longer utility runs, a septic system, a well, or a driveway. It's fair to say you usually get more space per dollar, not that the project is cheap."
      },
      {
        "q": "Won't a metal building be cold, or loud in the rain?",
        "a": "Only if it's insulated like a barn. Done properly — closed-cell spray foam against the shell, a deliberate vapor strategy, sealed penetrations and the right underlayment — a barndominium is quiet and holds temperature as well as a conventional house. This is the single biggest thing people get wrong, which is why it's a line item on every quote we write."
      },
      {
        "q": "Can I put a workshop or garage under the same roof?",
        "a": "Yes, and it's one of the main reasons people choose this build. The shop side needs its own treatment though — fire separation between the shop and living space, separate heating, and drainage if you'll be working on vehicles. We plan those in from the start rather than retrofitting them."
      },
      {
        "q": "Do you build the shell, or only finish the inside?",
        "a": "Either. We do complete turnkey builds, and we also finish out shells that are already standing — including barns and outbuildings being converted to living space. If you've already got a shell up, we'll assess what's there before quoting the finish-out."
      },
      {
        "q": "How long does it take?",
        "a": "Longer than a remodel — you're adding site work, a foundation and a shell to everything that goes inside. The honest answer is that it depends on your parcel and your county's review times. We give you a realistic written schedule once the site review and design are settled."
      },
      {
        "q": "What does it cost?",
        "a": "It varies more than anything else we build — a shell finish-out and a turnkey build on raw land aren't in the same range, and site conditions move the number a lot. Once we've walked the property and settled the scope, you get one itemized, fixed-price contract. See our financing page for current options, and note that a ground-up build is typically financed differently from a remodel."
      }
    ],
    "budget": null
  },
  {
    "slug": "custom-homes",
    "name": "Custom Homes",
    "short": "Ground-up homes designed around how you actually live — one team, one contract, one fixed price.",
    "image": "/assets/service-custom-home.webp",
    "order": 11,
    "metaTitle": "Custom Homes",
    "metaDescription": "Custom home design and construction across Greater Cincinnati, Northern Kentucky and Southeast Indiana. Design-build or build to your plans, with fixed pricing and a lifetime workmanship warranty.",
    "eyebrow": "Serving Ohio, Kentucky & Indiana",
    "title": "Custom Homes, Built by One Team",
    "region": "Design-build and build-to-plan homes across Greater Cincinnati, Northern Kentucky and Southeast Indiana",
    "whyTitle": "The House You Actually Want",
    "whyBody": "A production home is a floor plan someone else chose, with three finish packages and a lot number. A custom home starts from the other end: how your family really uses a house — where the light lands in the morning, whether the kitchen opens to the yard, how many people are actually home at 6pm. We've spent years being the people who fix production-built kitchens and baths that never worked, so we know exactly which decisions people regret. Building the whole house is the same work at a different scale: one accountable team, one contract, one fixed price, and a dedicated project manager from the first sketch to the final walkthrough.",
    "includesTitle": "What Every Custom Home Build Includes",
    "includes": [
      {
        "title": "Lot & Feasibility Review",
        "body": "Before you commit, we look at what the site will actually take — soils, slope, setbacks, utilities, access and what the zoning allows. Some lots cost far more to build on than they look."
      },
      {
        "title": "Permits & Inspections Managed",
        "body": "We pull the permits, book every inspection and keep the paperwork moving so you're not chasing a plans examiner."
      },
      {
        "title": "In-House Design & 3D Renderings",
        "body": "Your designer plans the layout, storage, lighting and finishes, and you walk the house in 3D before a single footing is poured."
      },
      {
        "title": "Foundation & Framing",
        "body": "Footings, foundation, framing, roofing and exterior — engineered for your site and inspected at every stage."
      },
      {
        "title": "The Envelope, Done Properly",
        "body": "Insulation, air sealing and windows specified for Ohio Valley winters. Getting this right during framing costs a fraction of fixing it later, and it's what your heating bill answers to for the next thirty years."
      },
      {
        "title": "Kitchens & Baths",
        "body": "The rooms we're known for, built to the same standard as everything in our portfolio — not the builder-grade versions you'd replace in five years."
      },
      {
        "title": "Utilities Run & Connected",
        "body": "Electrical service and panel, plumbing supply and drainage, HVAC sized for the house you're actually getting, plus septic and well coordination where there's no municipal hookup."
      },
      {
        "title": "Fixed Price, Itemized",
        "body": "One contract listing every material, finish and scope detail. Allowances are written as real numbers, not placeholders that quietly grow."
      },
      {
        "title": "Lifetime Workmanship Warranty",
        "body": "The same Lifetime Workmanship Warranty that backs every project we build backs the whole house. If it isn't right, we make it right."
      }
    ],
    "turnaroundTitle": "Settled Before We Break Ground",
    "turnaroundBody": "Most custom home horror stories start the same way: construction begins before the decisions are made, and every unmade choice becomes a change order. We work backwards from that. Design is finished, selections are made, allowances are real numbers, permits are filed and materials are ordered before the excavator arrives. That front-loading is why we can hand you a fixed price and a written schedule — and why the number you approve is the number you pay.",
    "closingQuote": "Got a lot already, or still looking for one? Either way that's the right first conversation — book an in-home consultation and we'll talk it through.",
    "faqs": [
      {
        "q": "Do I need to own land first?",
        "a": "No, but it changes where we start. If you already have a lot, the first step is a feasibility review of that specific site. If you're still looking, we'd rather look at candidates with you before you buy — the difference between an easy lot and a difficult one can be tens of thousands of dollars in site work, and it isn't obvious from the listing."
      },
      {
        "q": "Can I bring my own architect or plans?",
        "a": "Yes. We build to plans you already have, and we also do design-build where our in-house designer handles it start to finish. If you're bringing plans, we'll review them for constructability and cost before quoting — it's better to raise an issue at the drawing stage than at framing."
      },
      {
        "q": "How is this different from buying a production or spec home?",
        "a": "A production builder sells a fixed set of plans with a few finish packages, built at volume. Custom means the plan is drawn for your family and your lot, and the specification is yours — including the parts you can't see later, like insulation, windows and mechanicals. It costs more per square foot and it takes longer. What you get is a house that fits."
      },
      {
        "q": "How do you keep the price from creeping?",
        "a": "By finishing the decisions before construction starts and writing allowances as real numbers rather than placeholders. Most overruns aren't the builder's greed — they're a kitchen that was never fully specified, priced optimistically, then chosen for real in month four. We'd rather have that conversation up front."
      },
      {
        "q": "How long does a custom home take?",
        "a": "Longer than a remodel, and it depends on the design, your lot and your jurisdiction's review times. We won't quote a number before we've seen the site and settled the scope. Once design and permits are sorted you get a realistic written schedule, a dedicated project manager and regular updates."
      },
      {
        "q": "What does a custom home cost?",
        "a": "It depends on size, site and specification, and honestly ranges too widely for a number here to be useful. What we can commit to is that once the design is settled you get one itemized, fixed-price contract covering everything. See our financing page for current options — note that a ground-up build is financed differently from a remodel."
      },
      {
        "q": "Can you build in a particular style?",
        "a": "Yes. We build traditional, transitional and modern, and we're comfortable matching a neighborhood's character where that matters — or a deed restriction requires it. Style is a design conversation, not a constraint on who builds it."
      },
      {
        "q": "Can you tear down and rebuild on an existing lot?",
        "a": "Yes, and it's increasingly common in established neighborhoods where the location is right but the house isn't. Demolition, utility disconnects and reconnects, and any historic or overlay-district review get handled as part of the same contract."
      }
    ],
    "budget": null
  }
];

export const services: Record<string, Service> = Object.fromEntries(
  serviceList.map((s) => [s.slug, s]),
);
